version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout

      # This makes sure Chrome is always up to date in your test suite
      # On average this adds about 10 seconds to your build suite
      # Requires Ubuntu 14.04 (Trusty) in the CircleCI's OS setting (Settings > Build Environment)
      - run:
          name: Update Chrome
          command: |
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt-get install libappindicator3-1
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb

      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build and test
          command: npm test
